### ISSUE TITLE
Example on how to create .wav file

### ISSUE THREAD

**Issue by jknightdoeswork** [charstorm/koelsynth#2]
Simple.py is a good example, but it generates raw audio data. An example on how to generate a .wav file would be useful. I want to use koelsynth to generate tones as files. ie: A440.wav, etc. I tried to make simple.py generate a wav file instead, but I failed.

**Comment by charstorm** [comment]
I have added an example for that. Please see the following scripts.

- https://github.com/charstorm/koelsynth/blob/main/examples/simple/single_key_wav.py
- https://github.com/charstorm/koelsynth/blob/main/examples/simple/convert_audio.sh

**Comment by jknightdoeswork** [comment]
Great work. Nice project. The readme is nice. Well done!
